<?php
/**
 * @file
 * Extension of Islandora Bookmark that allows for mass downloading of content.
 */

/**
 * Implements hook_menu().
 */
function islandora_zip_download_menu() {
  $items = array();
  $items['admin/islandora/tools/islandora-zip-download'] = array(
    'title' => 'Islandora ZIP Download',
    'description' => 'Configure settings for the Islandora ZIP download module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_zip_download_admin_form'),
    'access arguments' => array('administer islandora_zip_download'),
    'file' => 'includes/admin.form.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function islandora_zip_download_permission() {
  return array(
    'administer islandora_zip_download' => array(
      'title' => t('Administer Islandora ZIP Download'),
      'description' => t('Perform administration tasks for Islandora ZIP Download.'),
    ),
  );
}

/**
 * Implements hook_islandora_bookmark_export_handler().
 */
function islandora_zip_download_islandora_bookmark_export_handler() {
  return array(
    t('ZIP Download') => array(
      'ZIP' => 'islandora_zip_download_generate_manifest',
    ),
  );
}

/**
 * Callback to generate a manifest for a ZIP.
 *
 * @param array $pids
 *   An array of PIDs to export.
 * @param NULL|string $style
 *   The style to be used for exporting, or NULL if not defined.
 * @param array $form_state
 *   The form state of the form where the export is being triggered.
 */
function islandora_zip_download_generate_manifest($pids, $style, $form_state) {
  global $user;
  // Get the selected MIME types to pass off from the UI. Note that the bookmark
  // form uses #tree and the Solr results doesn't.
  $mime_types = array();
  if (isset($form_state['values']['bookmarks']['fieldset']['file_types'])) {
    if (!empty($form_state['values']['bookmarks']['fieldset']['file_types'])) {
      $mime_types = $form_state['values']['bookmarks']['fieldset']['file_types'];
    }
    else {
      $mime_types = $form_state['complete form']['bookmarks']['fieldset']['file_types']['#options'];
    }
  }
  elseif (isset($form_state['values']['file_types'])) {
    if (!empty($form_state['values']['file_types'])) {
      $mime_types = $form_state['values']['file_types'];
    }
    else {
      $mime_types = $form_state['complete form']['islandora_bookmark_export']['fieldset']['file_types']['#options'];
    }
  }
  $pids_to_filter = array_map('trim', array_filter(explode(',', variable_get('islandora_zip_download_pids_to_exclude', ''))));
  $dsids_to_filter = array_map('trim', array_filter(explode(',', variable_get('islandora_zip_download_dsids_to_exclude', ''))));
  $mimes_to_filter = array_map('trim', array_filter(explode(',', variable_get('islandora_zip_download_mimes_to_exclude', ''))));
  $pids_to_export = array_diff($pids, $pids_to_filter);
  $mimes_to_export = array_diff($mime_types, $mimes_to_filter);
  if (empty($pids_to_export)) {
    form_set_error('bookmarks][fieldset', t('No PIDs to export.'));
  }
  // XXX: This is where the manifest creation gets pushed out to Gearman. Pass
  // on the PIDs, MIME types to filter and any DSID restrictions.
  islandora_job_submit_background('islandora_zip_download_generate_zip', array(
    'user_id' => $user->uid,
    'accessed_base_url' => $GLOBALS['base_url'],
    'mimes' => array(
      'all' => $mime_types,
      'exclude' => $mimes_to_filter,
      'filtered' => $mimes_to_export,
    ),
    'dsids' => array(
      'exclude' => $dsids_to_filter,
    ),
    'pids' => array(
      'base' => $pids,
      'exclude' => $pids_to_filter,
      'filtered' => $pids_to_export,
    ),
  ));
  drupal_set_message(t('The ZIP generation job has been queued. An e-mail will be sent when complete.'));
}

/**
 * Implements hook_form_FORMID_alter().
 */
function islandora_zip_download_form_islandora_bookmark_results_form_alter(&$form, &$form_state) {
  if (user_access('export islandora bookmarks')) {
    islandora_zip_download_file_type_export_element($form, 'islandora_bookmark_export');
  }
}

/**
 * Implements hook_form_FORMID_alter().
 */
function islandora_zip_download_form_islandora_bookmark_detailed_form_alter(&$form, &$form_state) {
  if (user_access('export islandora bookmarks')) {
    islandora_zip_download_file_type_export_element($form, 'bookmarks');
  }
}

/**
 * Helper to return the file type export for a form.
 *
 * @param array $form
 *   The form for the element to be inserted into.
 * @param string $parent_element
 *   The ID of the parent element where the element will be inserted. Also used
 *   for the states selector.
 */
function islandora_zip_download_file_type_export_element(&$form, $parent_element) {
  module_load_include('inc', 'islandora_zip_download', 'includes/utilities');
  $options = islandora_zip_download_mimetypes_to_export();
  if ($options) {
    $form[$parent_element]['fieldset']['file_types'] = array(
      '#type' => 'select',
      '#title' => t('File types'),
      '#description' => t('Select the types of MIMEs to be included in the ZIP. If none are selected all types will be included.'),
      '#multiple' => TRUE,
      '#options' => $options,
      // Using 4.1 to place this directly under the existing Bookmark select.
      '#weight' => 4.1,
      '#states' => array(
        'visible' => array(
          array(
            array(":input[name='bookmarks[fieldset][export_options]']" => array('value' => 'ZIP')),
            'or',
            array(":input[name='export_options']" => array('value' => 'ZIP')),
          ),
        ),
      ),
    );
  }
}

/**
 * Implements hook_islandora_job_register_jobs().
 */
function islandora_zip_download_islandora_job_register_jobs() {
  $job = array();

  $job['islandora_zip_download_generate_zip'] = array(
    'type' => 'inc',
    'module' => 'islandora_zip_download',
    'name' => 'includes/generate-zip.job',
    'alias' => 'izd-gz',
  );

  return $job;
}

/**
 * Rules getter callback; interpret integer as a filesize.
 */
function islandora_zip_download_rules_file_size_to_human_readable($data, array $options, $name, $type, $info) {
  module_load_include('inc', 'islandora', 'includes/utilities');
  return islandora_convert_bytes_to_human_readable($data);
}

/**
 * Implements hook_cron().
 */
function islandora_zip_download_cron() {
  module_load_include('inc', 'islandora_zip_download', 'includes/garbage-collection');
  islandora_zip_download_collect_garbage();
}

/**
 * Implements hook_tokens().
 */
function islandora_zip_download_tokens($type, $tokens, array $data = array(), array $options = array()) {
  static $types = NULL;
  if ($types === NULL) {
    $types = array_keys(module_invoke('islandora_zip_download', 'rules_data_info'));
  }
  if (in_array($type, $types)) {
    // XXX: Rules is silly, and does not automatically expose tokens for types
    // from hook_rules_data_info()... Let's roll ours.
    $cache = rules_get_cache();
    $data_info = $cache['data_info'];

    $wrapper = entity_metadata_wrapper('struct', $data[$type], $data_info[$type]);
    return entity_token_tokens('struct', $tokens, array('struct' => $wrapper), $options);
  }
}
